version: '2'

x-build-opts: &x-build-opts
  build:
    context: .

x-logging-opts: &x-logging-opts
  logging:
    driver: 'json-file'
    options:
      max-size: '20M'
      max-file: '5'

services:

  genesis:
    <<: *x-build-opts
    <<: *x-logging-opts
    image: maliciousgenius/doer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./space:/space:rw
