version: '2'

x-build-opts: &x-build-opts
  build:
    context: .
    dockerfile: ./Dockerfile

x-logging-opts: &x-logging-opts
  logging:
    driver: 'json-file'
    options:
      max-size: '20M'
      max-file: '5'

services:

  genesis:
    <<: *x-build-opts
    <<: *x-logging-opts
    environment:
      - JUPYTER_ENABLE_LAB="yes"
    volumes:
      - './work:/home/jovyan/work:rw'
    ports:
      - '8888:8888/tcp'
